
let para = [

    `{<h1> this is first para</h1>}Paragraph 1Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
    JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
    Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
    Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]Paragraph 2Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
    JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
    Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
    Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
    Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded Paragraph 2Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
    JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
    Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
    Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
    Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded Paragraph 2Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
    JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
    Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
    Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
    Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded Paragraph 2Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
    JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
    Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
    Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
    Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded 
    Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded            
        
        
        
        `,


`PARAGRAPH2:-   Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded    Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded   Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded   Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded   Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded   Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded       `

,
`PARAGRAPH 3:- Paragraph 1. Desktop applications such as web browsers and Microsoft Office and LibreOffice and WordPerfect, as well as smartphone and tablet applications (called).[citation needed]
JavaScript scripts are pieces of software traditionally embedded in web pages that are run directly inside the web browser when a web page is loaded without the need for a web browser plugin.Software written in other programming languages can also be run within the web browser if the software is either translated into JavaScript, or if a web browser plugin that supports that language is installed; the most common example of the latter is ActionScript scripts, which are supported by the Adobe Flash plugin.[citation needed]
Server software, including Web applications, which usually run on the web server and output dynamically generated web pages to web browsers, using e.g.PHP, Java, ASP.NET, or even JavaScript that runs on the server.In modern times these commonly include some JavaScript to be run in the web browser as , in which case they typically run partly on the server, partly in the web browser.[citation needed]
Plugins and extensions are software that extends or modifies the functionality of another piece of software, and require that software be used in order to function.[15]
Embedded software resides afirmware within embedded systems, devices dedicated to a single use or a few uses such ascars and televisions(although some embedded`

  ]

  export default para;
